name: linting, testing, building
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-ui-testing:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: install dependencies
        run: npm ci --force
      - name: build project
        run: npm run build
        if: always()
      - name: build storybook
        run: npm run build-storybook
        if: always()
      - name: screenshot testing
        run: npm run test:ui:ci
        if: always()
      - name: Generate HTML report
        run: npm run test:ui:report
        if: always()
      - name: unit testing
        run: npm run test:unit
        if: always()
      - name: move loki report
        run: mv .loki reports/
        if: always()
      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: always()
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'reports'
        if: always()
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: always()

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: install dependencies
        run: npm ci --force
      - name: typecheck (tsc)
        run: npm run typecheck
      - name: lint typescript files
        run: npm run lint:ts
        if: always()
      - name: lint scss
        run: npm run lint:scss
        if: always()
