name: CI Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js 17
        uses: actions/setup-node@v1
        with:
          node-version: '17'
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: lint typescript
        run: npm run lint:ts
      - name: lint scss
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run build-storybook
      - name: screenshot testing
        run: npm run test:ui:ci
