name: linting, testing, building
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-ui-testing:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci --force
      - name: build project
        run: npm run build
      - name: build storybook
        run: npm run build-storybook
      - name: screenshot testing
        run: npm run test:ui:ci
      - name: Generate HTML report
        run: npm run test:ui:report
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.loki'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci --force
      - name: lint typescript
        run: npm run lint:ts
      - name: lint scss
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit