name: CI Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js '17'
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: install dependencies
        run: npm ci
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js '17'
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: install dependencies
        run: npm ci
      - name: lint typescript
        run: npm run lint:ts
      - name: lint scss
        run: npm run lint:scss
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js '17'
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: install dependencies
        run: npm ci
      - name: unit testing
        run: npm run test:unit
  screenshot-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js '17'
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: install dependencies
        run: npm ci
      - name: build storybook
        run: npm run build-storybook
      - name: screenshot testing
        run: npm run test:ui:ci
  